stages:
  - build
  - cleanup

build:
  stage: build
  script:
      - cp .env-dist .env
      - cp docker-compose.override-dist.yml docker-compose.override.yml
      - docker-compose run --rm php composer install
      - docker-compose up -d
      - docker-compose ps
      - docker-compose stop
      - docker-compose kill rm -fv

cleanup:
  stage: cleanup
  script:
      - docker-compose kill
      - docker-compose rm -fv
  when: always