# Phundament nano

php:
  build: .
  environment:
    - YII_ENV=dev
    - YII_DEBUG=1
  links:
    - 'percona:DB'
  volumes:
    - ./composer.json:/app/composer.json
    - ./composer.lock:/app/composer.lock
    - ./vendor:/app/vendor
    - ./.env:/app/.env
    - ./src/config/local.php:/app/src/config/local.php
    - ./modules:/app/modules

nginx:
  ports:
    - '8023:80'

percona:
  environment:
    MYSQL_ROOT_PASSWORD: secretadmin
  ports:
    - 33023:3306
